version: "3.8"
services:
  database:
    container_name: database
    build: ./database
    image: 1m0gen/project-database
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
  frontend:
    container_name: frontend
    build: ./frontend
    image: 1m0gen/project-frontend  
  backend:
    container_name: backend
    build: ./backend
    image: 1m0gen/project-backend  
